from dotenv import load_dotenv
import os

load_dotenv()

OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
INSTANCE_FAISS_PATH = os.getenv("INSTANCE_FAISS_PATH")
INSTANCE_CSV_PATH = os.getenv("INSTANCE_CSV_PATH")
DB_FAISS_PATH = os.getenv("DB_FAISS_PATH")
DB_CSV_PATH = os.getenv("DB_CSV_PATH")
OBJECT_STORAGE_FAISS_PATH = os.getenv("OBJECT_STORAGE_FAISS_PATH")
OBJECT_STORAGE_CSV_PATH = os.getenv("OBJECT_STORAGE_CSV_PATH")